# Generated by Django 5.2.5 on 2025-12-06 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish_date"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="published",
            new_name="publish_date",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-publish_date"], name="blog_post_publish_7e8b08_idx"
            ),
        ),
    ]
