# Generated by Django 5.2.5 on 2025-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_493ec4_idx",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish_date"),
        ),
    ]
