# Generated by Django 5.2.8 on 2025-12-28 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-publication_date", "title"]},
        ),
        migrations.AlterModelOptions(
            name="bookcontributor",
            options={"ordering": ["role", "contributor__last_names"]},
        ),
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["last_names", "first_names"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RemoveField(
            model_name="book",
            name="contributor",
        ),
        migrations.AddField(
            model_name="book",
            name="contributors",
            field=models.ManyToManyField(
                related_name="books",
                through="reviews.BookContributor",
                to="reviews.contributor",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="book_covers/",
                verbose_name="Book Cover",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(db_index=True, verbose_name="Publication date"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="reviews.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                db_index=True, help_text="The title of the book", max_length=70
            ),
        ),
        migrations.AlterField(
            model_name="bookcontributor",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_contributors",
                to="reviews.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookcontributor",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_contributions",
                to="reviews.contributor",
            ),
        ),
        migrations.AlterField(
            model_name="bookcontributor",
            name="role",
            field=models.CharField(
                choices=[
                    ("AUTHOR", "Author"),
                    ("CO_AUTHOR", "Co-Author"),
                    ("EDITOR", "Editor"),
                ],
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(
                help_text="The contributor's email", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="first_names",
            field=models.CharField(
                help_text="First name of contributor", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="last_names",
            field=models.CharField(
                db_index=True, help_text="Last name of contributor", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(
                db_index=True, help_text="The name of the Publisher.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                help_text="The book that this review is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.book",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(
                blank=True, help_text="Provide a detailed review of the book."
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time the review was created"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="date_edited",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                help_text="Date and time the review was last edited",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                help_text="The rating that the reviewer has given (1-5)",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["title", "publication_date"],
                name="reviews_boo_title_6fb8fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["isbn"], name="reviews_boo_isbn_52f4a8_idx"),
        ),
        migrations.AddIndex(
            model_name="bookcontributor",
            index=models.Index(
                fields=["book", "role"], name="reviews_boo_book_id_904d7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["last_names", "first_names"],
                name="reviews_con_last_na_3dda5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publisher",
            index=models.Index(fields=["name"], name="reviews_pub_name_3ecd40_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["book", "-date_created"], name="reviews_rev_book_id_0beb41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["creator", "-date_created"],
                name="reviews_rev_creator_7d9cc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-rating"], name="reviews_rev_rating_f8028e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookcontributor",
            constraint=models.UniqueConstraint(
                fields=("book", "contributor", "role"),
                name="unique_book_contributor_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("book", "creator"), name="unique_book_creator"
            ),
        ),
    ]
