# Generated by Django 5.2.5 on 2025-09-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_names",
                    models.CharField(
                        help_text="first name of contributor", max_length=50
                    ),
                ),
                (
                    "last_names",
                    models.CharField(
                        help_text="last name of contributor", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The publisher's email", max_length=254
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name of the Publisher.cation_dates",
                        max_length=50,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(verbose_name="saye book was published"),
                ),
                (
                    "isbn",
                    models.CharField(max_length=20, verbose_name="ISBN of the book"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUTHOR", "Author"),
                            ("CO_AUTHOR", "Co-Author"),
                            ("EDITOR", "Editor"),
                        ],
                        max_length=20,
                        verbose_name="The role this contributor had in the book.",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reviews.book"
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.contributor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="contributor",
            field=models.ManyToManyField(
                through="reviews.BookContributor", to="reviews.contributor"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Provide a detailed review of the book."
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(help_text="the rating this user ghas given"),
                ),
                (
                    "date_edited",
                    models.DateTimeField(
                        help_text="date and time the review was edited", null=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time the review was created",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="The book that this review is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
